### ISSUE TITLE
Error Running

### ISSUE THREAD

**Issue by yupysec22** [rameshrrl/tweets-deleter#9]
![gambar](https://user-images.githubusercontent.com/110398718/197341976-2709892d-56e9-47a9-948b-db803d0ccc98.png)

How to fix??

**Comment by rameshrrl** [comment]
Please take a look at the README file @yupysec22. You should remove these lines **window.YTD.tweets.part1 =**, while uploading it. Let it be an array of tweets only. It will work. I appreciate your efforts. Closing this issue upon the fix is already there in project README.

**Comment by rameshrrl** [comment]
Hey, @yupysec22. The issue has been fixed. Please take a pull or clone the latest version. I appreciate you for letting me know about the subject.
